CREATE DATABASE trans_ex;
USE trans_ex;
CREATE TABLE item (
	id			INT AUTO_INCREMENT PRIMARY KEY,
	barcode		VARCHAR(50) NOT NULL UNIQUE,
	name		VARCHAR (100) NOT NULL UNIQUE,
	price	INT NOT NULL DEFAULT 0
);
CREATE TABLE customer (
	id			INT AUTO_INCREMENT PRIMARY KEY,
	name		VARCHAR (100) NOT NULL
);
CREATE TABLE sales_order (
	id			INT AUTO_INCREMENT PRIMARY KEY,
	customer_id	INT,
	code		VARCHAR(50) NOT NULL UNIQUE,
	date		DATETIME NOT NULL,
	paid		INT NOT NULL DEFAULT 0,
	note		VARCHAR (1000) NOT NULL DEFAULT '',
	FOREIGN KEY (customer_id) REFERENCES customer (id) ON UPDATE CASCADE ON DELETE SET NULL
);
CREATE TABLE sales_order_detail (
	id			INT AUTO_INCREMENT PRIMARY KEY,
	sales_order_id	INT NOT NULL,
	item_id		INT NOT NULL,
	quantity	FLOAT NOT NULL DEFAULT 0,
	price		INT NOT NULL DEFAULT 0,
	FOREIGN KEY (sales_order_id) REFERENCES sales_order(id) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (item_id) REFERENCES item (id) ON UPDATE CASCADE ON DELETE CASCADE
);